version: '3'
services:

  face_detection:
    build:
      context: ./face_detection
      dockerfile: Dockerfile
    volumes:
      - ./face_detection:/code
    command: /bin/sh ./run.sh
    ports:
      - 9001:9000
    networks:
      - backend

  face_recognition:
    build:
      context: ./face_recognition
      dockerfile: Dockerfile
    volumes:
      - ./face_recognition:/code
    command: /bin/sh ./run.sh
    ports:
      - 9002:9000
    networks:
      - backend

  mongo_crud:
    build:
      context: ./mongo_crud
      dockerfile: Dockerfile
    volumes:
      - ./mongo_crud:/code
    command: /bin/sh ./run.sh
    ports:
      - 9003:9000
    networks:
      - backend

  mongo:
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
