version: '3'
services:

  face_detection:
    build:
      context: ./face_detection
      dockerfile: Dockerfile
    image: pdm_face_detection
    volumes:
      - ./face_detection:/code
    command: /bin/sh ./run.sh
    ports:
      - 9001:9000

  face_recognition:
    build:
      context: ./face_recognition
      dockerfile: Dockerfile
    image: pdm_face_recognition
    volumes:
      - ./face_recognition:/code
    command: /bin/sh ./run.sh
    ports:
      - 9002:9000

  mongo_crud:
    build:
      context: ./mongo_crud
      dockerfile: Dockerfile
    volumes:
      - ./mongo_crud:/code
    command: /bin/sh ./run.sh
    env_file: 
      - ./mongo_crud/environment
    ports:
      - 9003:9000

  postgres_crud:
    build:
      context: ./postgres_crud
      dockerfile: Dockerfile
    env_file: 
      - ./postgres_crud/environment
    volumes:
      - ./postgres_crud:/code
    command: /bin/sh ./run.sh
    ports:
      - 9004:9000

  mongo:
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    image: pdm_mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pdm123
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: lulapt13
      ME_CONFIG_MONGODB_SERVER: mongo

  postgres:
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"